# Generated by Django 2.2.3 on 2019-08-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': (['due_back'],), 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
